### ISSUE TITLE
当项目中依赖的第三方库使用了与你版本不同的glide库时就冲突了，闪退！

### ISSUE THREAD

**Issue by manburenshenglu** [HuanTanSheng/EasyPhotos#120]
java.lang.NoSuchMethodError: No virtual method setDecodeFormat(Lcom/bumptech/glide/load/DecodeFormat;)Lcom/bumptech/glide/GlideBuilder; in class Lcom/bumptech/glide/GlideBuilder; or its super classes (declaration of 'com.bumptech.glide.GlideBuilder' appears in /data/app/com.jaagro.driver-LrdOId9aWdj8Ce1TLOgnpQ==/base.apk)
        at cc.shinichi.library.glide.engine.OkHttpProgressGlideModule.applyOptions(OkHttpProgressGlideModule.java:61)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:263)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:223)
        at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:184)
        at com.bumptech.glide.Glide.get(Glide.java:168)
        at com.bumptech.glide.Glide.getRetriever(Glide.java:689)
        at com.bumptech.glide.Glide.with(Glide.java:716)

**Comment by HuanTanSheng** [comment]
本框架并没有引用任何版本的glide，图片展示的相关实现是由接口做的。

**Comment by manburenshenglu** [comment]
![image](https://user-images.githubusercontent.com/13146756/79859818-2ee95280-8404-11ea-81c5-3cd283001022.png)
哦哦明白了，也就是说，红框中的代码我还是可以使用与项目中第三方库中相同的glide版本。多谢楼主分享这么好的库
