### ISSUE TITLE
闪退了

### ISSUE THREAD

**Issue by zijinzhiyun** [HuanTanSheng/EasyPhotos#13]
我是最大选择9张，选了9张后，在最后一张上点击选择按钮，无效，一直点击就会出现空指针
java.lang.RuntimeException: Unable to resume activity {com.example.xintiaotime.androiddemo/com.huantansheng.easyphotos.ui.EasyPhotosActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=13, result=0, data=null} to activity {com.example.xintiaotime.androiddemo/com.huantansheng.easyphotos.ui.EasyPhotosActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setTextColor(int)' on a null object reference
                                                                                         at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3586)
                                                                                         at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3626)
                                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2876)
                                                                                         at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                         at android.os.Looper.loop(Looper.java:156)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
                                                                                      Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=13, result=0, data=null} to activity {com.example.xintiaotime.androiddemo/com.huantansheng.easyphotos.ui.EasyPhotosActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setTextColor(int)' on a null object reference
                                                                                         at android.app.ActivityThread.deliverResults(ActivityThread.java:4284)
                                                                                         at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3558)
                                                                                         at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3626) 
                                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2876) 
                                                                                         at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567) 
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                                         at android.os.Looper.loop(Looper.java:156) 
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:6523) 
                                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
                                                                                      Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setTextColor(int)' on a null object reference
                                                                                         at com.huantansheng.easyphotos.ui.EasyPhotosActivity.processOriginalMenu(EasyPhotosActivity.java:578)
                                                                                         at com.huantansheng.easyphotos.ui.EasyPhotosActivity.onActivityResult(EasyPhotosActivity.java:312)
                                                                                         at android.app.Activity.dispatchActivityResult(Activity.java:7188)
                                                                                         at android.app.ActivityThread.deliverResults(ActivityThread.java:4280)
                                                                                         at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3558) 
                                                                                         at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3626) 
                                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2876) 
                                                                                         at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567) 
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                                         at android.os.Looper.loop(Looper.java:156) 
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:6523) 
                                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by HuanTanSheng** [comment]
感谢反馈，已修复
