### ISSUE TITLE
请问适配了【8.0非全屏无法设置方向】的问题吗

### ISSUE THREAD

**Issue by Alexyulu** [HuanTanSheng/EasyPhotos#134]
Build date: 2020-06-05 13:52:22 
Current date: 2020-06-06 09:24:10 
Device: Xiaomi MIX 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.unicdata.cheshangying/com.huantansheng.easyphotos.ui.EasyPhotosActivity}: **java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation**
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2856)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2931)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1620)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:173)
	at android.app.ActivityThread.main(ActivityThread.java:6698)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
Caused by: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
	at android.app.Activity.onCreate(Activity.java:1005)
	at android.support.v4.app.SupportActivity.onCreate(ComponentActivity.java:75)
	at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:335)
	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:85)
	at com.huantansheng.easyphotos.ui.EasyPhotosActivity.onCreate(Native Method)
	at android.app.Activity.performCreate(Activity.java:7040)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2809)
	... 9 more

**Comment by HuanTanSheng** [comment]
已修复
