### ISSUE TITLE
数组越界

### ISSUE THREAD

**Issue by zijinzhiyun** [HuanTanSheng/EasyPhotos#14]
java.lang.IndexOutOfBoundsException: Index: 8, Size: 8
                                                                                         at java.util.ArrayList.get(ArrayList.java:411)
                                                                                         at com.huantansheng.easyphotos.result.Result.getPhotoPath(Result.java:82)
                                                                                         at com.huantansheng.easyphotos.ui.PreviewActivity.onPreviewPhotoClick(PreviewActivity.java:416)
                                                                                         at com.huantansheng.easyphotos.ui.PreviewFragment.onPhotoClick(PreviewFragment.java:55)
                                                                                         at com.huantansheng.easyphotos.ui.adapter.PreviewPhotosFragmentAdapter$1.onClick(PreviewPhotosFragmentAdapter.java:63)
                                                                                         at android.view.View.performClick(View.java:5646)
                                                                                         at android.view.View$PerformClick.run(View.java:22459)
                                                                                         at android.os.Handler.handleCallback(Handler.java:761)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                         at android.os.Looper.loop(Looper.java:156)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by HuanTanSheng** [comment]
已修复
