### ISSUE TITLE
不知道为啥按照文档设置FileProvider还是不行

### ISSUE THREAD

**Issue by GirlFriendNotFind** [HuanTanSheng/EasyPhotos#146]
android10，红米k30pro
java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/DCIM/FanJu/IMG1602591016780.png
        at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:744)
        at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:418)
        at com.huantansheng.easyphotos.utils.uri.UriUtils.getUri(UriUtils.java:29)
        at com.huantansheng.easyphotos.ui.PuzzleActivity$4.onSuccess(PuzzleActivity.java:463)
        at com.huantansheng.easyphotos.utils.bitmap.BitmapUtils$3.run(BitmapUtils.java:285)
        at android.os.Handler.handleCallback(Handler.java:914)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:227)
        at android.app.ActivityThread.main(ActivityThread.java:7582)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)

**Comment by GirlFriendNotFind** [comment]
解决了，authorities冲突了，需要重命名
