### ISSUE TITLE
WindowLeaked 窗口泄露

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [HuanTanSheng/EasyPhotos#174]
我在使用EasyPhotos的时候，打开相册选择图片达到最大值之后再次选择这么多，没有清空选择的图片集list集合，第三次打开相册时候程序会停止运行，报窗口泄露的error

E/WindowManager: android.view.WindowLeaked: Activity com.huantansheng.easyphotos.ui.EasyPhotosActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{40ca484 V.ED.... R....... 0,0-720,75} that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:457)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:278)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
        at android.app.Dialog.show(Dialog.java:311)
        at com.huantansheng.easyphotos.ui.dialog.LoadingDialog.show(LoadingDialog.java:45)
        at com.huantansheng.easyphotos.ui.EasyPhotosActivity.hasPermissions(EasyPhotosActivity.java:207)
        at com.huantansheng.easyphotos.ui.EasyPhotosActivity.onCreate(EasyPhotosActivity.java:158)
        at android.app.Activity.performCreate(Activity.java:6092)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2481)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2608)
        at android.app.ActivityThread.access$800(ActivityThread.java:178)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5637)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

**Comment by HuanTanSheng** [comment]
这个真实报错原因不是窗口泄露，而是你传进来的已选图片集合的size大于最大可选数量了，这时我内部抛了个异常出来，告诉你不可以这样传，你应该可以在控制台看到log，同时这个异常导致activity销毁，导致窗口泄露。正是你复制的这段。
1 有时间我会处理一下这个问题，让log更直观，同时避免掉这个泄露。
2 正确的默认选择图片用法是，在返回数据处理时，先清空默认图片集合，再添加返回的已选择集合，就不会出错了。
