### ISSUE TITLE
java.lang.IllegalArgumentException: View=DecorView@5acff58[EasyPhotosActivity] not attached to window manager

### ISSUE THREAD

**Issue by 1wayticket** [HuanTanSheng/EasyPhotos#178]
Thread Name: 'main'
Back traces starts.
java.lang.IllegalArgumentException: View=DecorView@5acff58[EasyPhotosActivity] not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:610)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:502)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:175)
	at android.app.Dialog.dismissDialog(Dialog.java:754)
	at android.app.Dialog.dismiss(Dialog.java:734)
	at com.huantansheng.easyphotos.ui.EasyPhotosActivity$5$1.run(EasyPhotosActivity.java:573)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8387)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
Back traces ends.
sdk版本是最新的3.1.3
应该是极限情况下dialog脱离activity 导致dialog消失报错
麻烦保护下

**Comment by zwwxj** [comment]
同样报错，麻烦保护下
