### ISSUE TITLE
Android模拟器有的没有相机，点击拍照按钮会直接奔溃

### ISSUE THREAD

**Issue by ZSFeng** [HuanTanSheng/EasyPhotos#221]
`UncaughtException detected: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zy.mos/com.huantansheng.easyphotos.ui.EasyPhotosActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 clip={text/uri-list U:content://com.zy.mos.fileProvider/external/Pictures/IMG837843194.jpg} (has extras) }
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2670)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1482)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6161)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)`

**Comment by Justin777s** [comment]
调用前判断拍照是否可用

```kotlin    
   fun isEnable(context:Context):Boolean{
            var captureIntent = Intent("android.media.action.IMAGE_CAPTURE");
            if (captureIntent.resolveActivity(context.getPackageManager()) != null) {
                return true
            }
            return false;
        }
```

**Comment by wzgl5533** [comment]
模拟器在笔记本上应该能启动自带的摄像头吧，我有个app是自定义相机拍照，完全可以兼容。本库后续是否可以兼容呢？
![image](https://github.com/HuanTanSheng/EasyPhotos/assets/11958496/492f5dcb-7187-4059-8d19-c8646089a19d)
