### ISSUE TITLE
闪退 EasyPhotosActivity

### ISSUE THREAD

**Issue by 912334508** [HuanTanSheng/EasyPhotos#223]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.renameTo(java.io.File)' on a null object reference
	at com.huantansheng.easyphotos.ui.EasyPhotosActivity$5.run(EasyPhotosActivity.java:607)
	at java.lang.Thread.run(Thread.java:764)

**Comment by 912334508** [comment]
3.1.4
