### ISSUE TITLE
Android 4.4.3的手机，使用相机的时候报错了！

### ISSUE THREAD

**Issue by DevXue** [HuanTanSheng/EasyPhotos#23]
02-02 20:39:54.321 9868-9868/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.android.camera2, PID: 9868
                                                 java.lang.SecurityException: Permission Denial: opening provider android.support.v4.content.FileProvider from ProcessRecord{427bc788 9868:com.android.camera2/u0a40} (pid=9868, uid=10040) that is not exported from uid 10011
                                                     at android.os.Parcel.readException(Parcel.java:1472)
                                                     at android.os.Parcel.readException(Parcel.java:1426)
                                                     at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:2860)
                                                     at android.app.ActivityThread.acquireProvider(ActivityThread.java:4459)
                                                     at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2208)
                                                     at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1425)
                                                     at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:906)
                                                     at android.content.ContentResolver.openOutputStream(ContentResolver.java:669)
                                                     at android.content.ContentResolver.openOutputStream(ContentResolver.java:645)
                                                     at com.android.camera.PhotoModule.onCaptureDone(PhotoModule.java:1525)
                                                     at com.android.camera.PhotoUI$4.onClick(PhotoUI.java:436)
                                                     at android.view.View.performClick(View.java:4615)
                                                     at android.view.View$PerformClick.run(View.java:18784)
                                                     at android.os.Handler.handleCallback(Handler.java:733)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5061)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:603)
                                                     at dalvik.system.NativeStart.main(Native Method)
02-02 20:39:57.041 1518-8030/? E/HttpSender: IOException while sending report: failed to connect to er.ydevices.com/5.200.42.210 (port 80) after 6000ms
02-02 20:40:06.051 1518-8030/? E/HttpSender: IOException while sending report: failed to connect to er.ydevices.com/5.200.42.210 (port 80) after 9000ms
02-02 20:40:06.051 1518-8030/? E/ReportUploadService: Failed to send report 1517331601000_359694060470397.usagestats.txt.gz
                                                      com.yotadevices.crashreportuploader.ReportSenderException: IOException while sending report(retries exceeded)
                                                          at com.yotadevices.crashreportuploader.HttpSender.sendUsageStats(HttpSender.java:274)
                                                          at com.yotadevices.crashreportuploader.ReportUploadService.checkAndSendReports(ReportUploadService.java:123)
                                                          at com.yotadevices.crashreportuploader.ReportUploadService.onHandleIntent(ReportUploadService.java:85)
                                                          at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                          at android.os.Looper.loop(Looper.java:136)
                                                          at android.os.HandlerThread.run(HandlerThread.java:61)
                                                       Caused by: java.net.SocketTimeoutException: failed to connect to er.ydevices.com/5.200.42.210 (port 80) after 9000ms
                                                          at libcore.io.IoBridge.connectErrno(IoBridge.java:159)
                                                          at libcore.io.IoBridge.connect(IoBridge.java:112)
                                                          at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
                                                          at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:460)
                                                          at java.net.Socket.connect(Socket.java:833)
                                                          at com.android.okhttp.internal.Platform.connectSocket(Platform.java:152)
                                                          at com.android.okhttp.Connection.connect(Connection.java:101)
                                                          at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
                                                          at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
                                                          at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
                                                          at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
                                                          at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
                                                          at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:197)
                                                          at com.yotadevices.crashreportuploader.HttpSender.sendUsageStats(HttpSender.java:227)
                                                          at com.yotadevices.crashreportuploader.ReportUploadService.checkAndSendReports(ReportUploadService.java:123) 
                                                          at com.yotadevices.crashreportuploader.ReportUploadService.onHandleIntent(ReportUploadService.java:85) 
                                                          at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65) 
                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                          at android.os.Looper.loop(Looper.java:136) 
                                                          at android.os.HandlerThread.run(HandlerThread.java:61) 
02-02 20:40:09.071 1518-8030/? E/HttpSender: IOException while sending report: failed to connect to er.ydevices.com/5.200.42.210 (port 80) after 3000ms
02-02 20:40:15.101 1518-8030/? E/HttpSender: IOException while sending report: failed to connect to er.ydevices.com/5.200.42.210 (port 80) after 6000ms

很奇怪的问题，  我用4.4.3的手机测试(手机品牌为： YouTaPhone)  相机的时候  提示我相机停止运行，而不是这个demo停止运行   不明白咋回事，另外使用其他的库没发现相机停止运行的问题

**Comment by HuanTanSheng** [comment]
@DevXue 
感谢反馈，请问这个是用EasyPhotos的Demo跑出的错误信息吗？

**Comment by DevXue** [comment]
@HuanTanSheng  嗯，  难道你没有看到我下面的那段话么？ 
是这个Demo 跑出的问题  4.4.3手机使用相机功能的时候：提示相机停止运行，而不是 easyPhoto 停止运行···   不知道咋回事。

**Comment by HuanTanSheng** [comment]
@DevXue 
OK，已修复。
麻烦下载dev分支代码进行测试，测试通过后我将合并分支，静候佳音，感谢。

**Comment by DevXue** [comment]
@HuanTanSheng   666   可以了！  多谢。
