### ISSUE TITLE
3.1.5版本，崩溃问题。Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.android.packageinstaller (has extras) }

### ISSUE THREAD

**Issue by liquor2020** [HuanTanSheng/EasyPhotos#256]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.test.test.test/com.huantansheng.easyphotos.ui.EasyPhotosActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.android.packageinstaller (has extras) }
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3211)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3348)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2074)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7113)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)
Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.android.packageinstaller (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2016)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1813)
	at android.app.Activity.startActivityForResult(Activity.java:5380)
	at android.app.Activity.requestPermissions(Activity.java:4580)
	at androidx.appcompat.widget.a.r(R8$$SyntheticClass:1)
	at androidx.core.app.ActivityCompat$Api23Impl.requestPermissions(ActivityCompat.java:1)
	at androidx.core.app.ActivityCompat.requestPermissions(ActivityCompat.java:66)
	at t1.a.a(PermissionUtil.java:43)
	at com.huantansheng.easyphotos.ui.EasyPhotosActivity.onCreate(EasyPhotosActivity.java:205)
	at android.app.Activity.performCreate(Activity.java:7250)
	at android.app.Activity.performCreate(Activity.java:7241)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3191)
	... 11 more
Back traces ends.

**Comment by PupilDamon** [comment]
您好，钟裕达已经收到您的来信并会尽快查收，谢谢！
