### ISSUE TITLE
华为nova 9z打开相机提示图片错误

### ISSUE THREAD

**Issue by 8023-Android** [HuanTanSheng/EasyPhotos#259]
java.lang.IllegalArgumentException: Primary directory pictures not allowed for content://media/external_primary/file; allowed directories are [Download, Documents]
        at com.android.providers.media.MediaProvider.ensureFileColumns(MediaProvider.java:3358)
        at com.android.providers.media.MediaProvider.ensureUniqueFileColumns(MediaProvider.java:3019)
        at com.android.providers.media.MediaProvider.insertFile(MediaProvider.java:3729)
        at com.android.providers.media.MediaProvider.insertInternal(MediaProvider.java:4364)
        at com.android.providers.media.MediaProvider.insert(MediaProvider.java:4034)
        at com.android.providers.media.MediaProvider.insertFileForFuse(MediaProvider.java:8137)
        at com.android.providers.media.MediaProvider.insertFileIfNecessaryForFuse(MediaProvider.java:8223)

**Comment by PupilDamon** [comment]
您好，钟裕达已经收到您的来信并会尽快查收，谢谢！
