### ISSUE TITLE
华为p10选择照片奔溃 android8.0

### ISSUE THREAD

**Issue by songsongtao** [HuanTanSheng/EasyPhotos#38]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.endsWith(java.lang.String)' on a null object reference

at com.huantansheng.easyphotos.models.album.AlbumModel.initAlbum(AlbumModel.java:129)

at com.huantansheng.easyphotos.models.album.AlbumModel.access$000(AlbumModel.java:29)

at com.huantansheng.easyphotos.models.album.AlbumModel$1.run(AlbumModel.java:65)

at java.lang.Thread.run(Thread.java:784)
```

**Comment by songsongtao** [comment]
@HuanTanSheng 不好意思打扰了，我就是在群里说解决这个问题，但是我发现部分手机号是会这样，但是自己测试没发现

**Comment by songsongtao** [comment]
@HuanTanSheng 
异常类型：java.lang.NullPointerException

异常信息：Attempt to invoke virtual method 'boolean java.lang.String.endsWith(java.lang.String)' on a null object reference

关键方法：com.huantansheng.easyphotos.models.album.AlbumModel.initAlbum(AlbumModel.java:129)

**Comment by HuanTanSheng** [comment]
该问题出现在2.3.3版本之前，之后的版本已经修复。
