### ISSUE TITLE
"拼一张"功能选择的图片过大导致oom

### ISSUE THREAD

**Issue by Beiler** [HuanTanSheng/EasyPhotos#4]
选择了9张拍的照片，然后就oom了
java.lang.OutOfMemoryError: Failed to allocate a 8294412 byte allocation with 6914568 free bytes and 6MB until OOM
                                                                  at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                  at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
                                                                  at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:639)
                                                                  at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:615)
                                                                  at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:391)
                                                                  at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:419)
                                                                  at com.huantansheng.easyphotos.ui.PuzzleActivity.getScaleBitmap(PuzzleActivity.java:330)
                                                                  at com.huantansheng.easyphotos.ui.PuzzleActivity.access$800(PuzzleActivity.java:60)
                                                                  at com.huantansheng.easyphotos.ui.PuzzleActivity$3.run(PuzzleActivity.java:274)
                                                                  at java.lang.Thread.run(Thread.java:818)

**Comment by HuanTanSheng** [comment]
@Beiler 
你好，Glide的问题已经解决，原因是Glide内部在4.4.0之后引入了com.android.support包，我们在引入的时候剔除掉这个包就可以。
方法如下：
    api ("com.github.bumptech.glide:glide:4.5.0") {
        exclude group: "com.android.support"
    }
注：api依赖方式是android studio 3.0版本新出的，对应android studio 3.0版本之前的compile依赖方式

拼一张的这个问题我大概解决了一下，你可以尝试2.0.2试一下。

**Comment by Beiler** [comment]
@HuanTanSheng 刚测试了下，完美没问题~

**Comment by HuanTanSheng** [comment]
@Beiler 感谢。我在ReadMe的更新日志提到你了，不介意吧~~~///(^v^)\\\~~~

**Comment by Beiler** [comment]
@HuanTanSheng 不介意的，哈哈

**Comment by HuanTanSheng** [comment]
@Beiler 
方便的话加一下QQ群：[288600953](https://jq.qq.com/?_wv=1027&k=5QGgCDe)      
有什么问题可以随时交流😏

**Comment by Beiler** [comment]
@HuanTanSheng 好的
