### ISSUE TITLE
EasyPhotos拍照保存的图片不存在

### ISSUE THREAD

**Issue by songsongtao** [HuanTanSheng/EasyPhotos#42]
`java.lang.RuntimeException: Unable to resume activity {com.zwang.znc/com.huantansheng.easyphotos.ui.EasyPhotosActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=11, result=-1, data=null} to activity {com.zwang.znc/com.huantansheng.easyphotos.ui.EasyPhotosActivity}: java.lang.RuntimeException: EasyPhotos拍照保存的图片不存在
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3790)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3830)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3038)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=11, result=-1, data=null} to activity {com.zwang.znc/com.huantansheng.easyphotos.ui.EasyPhotosActivity}: java.lang.RuntimeException: EasyPhotos拍照保存的图片不存在
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4491)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3762)
	... 10 more
Caused by: java.lang.RuntimeException: EasyPhotos拍照保存的图片不存在
	at com.huantansheng.easyphotos.ui.EasyPhotosActivity.onActivityResult(EasyPhotosActivity.java:318)
	at android.app.Activity.dispatchActivityResult(Activity.java:7556)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4487)
	... 11 more`

**Comment by HuanTanSheng** [comment]
请问用demo也会出现这种情况么？

**Comment by songsongtao** [comment]
就是部分图片不能选取，我用了qq都是一样，所以我就忽略了这个问题

**Comment by HuanTanSheng** [comment]
好的，如果没有问题，请关闭这条问题哦~
