### ISSUE TITLE
华为手机选择照相奔溃

### ISSUE THREAD

**Issue by saljfla** [HuanTanSheng/EasyPhotos#44]
E/MemoryLeakMonitorManager: MemoryLeakMonitor.jar is not exist!
 E/cr_VariationsUtils: Failed reading seed file "/data/user/0/com.xxx.xxx/app_webview/variations_seed_new": /data/user/0/com.xxx.xxx/app_webview/variations_seed_new (No such file or directory)
 E/CrashReport: --------------------------------------------------------------------------------------------
 E/CrashReport: --------------------------------------------------------------------------------------------
 E/Minikin: Could not get cmap table size!
 E/JVMContainer VMSG: RegisterNatives
 E/iGraphics: failed to load file: /product/etc/xml/igraphics_config_cust.xml

**Comment by HuanTanSheng** [comment]
你好，请问我的demo也是如此么？

**Comment by HuanTanSheng** [comment]
只看你给出的log的话，看不出与EasyPhotos有什么关系……

**Comment by saljfla** [comment]
> 只看你给出的日志的话，看不出与EasyPhotos有什么关系......

 java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
        at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:605)
        at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:579)
        at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:417)
        at com.huantansheng.easyphotos.ui.EasyPhotosActivity.toAndroidCamera(EasyPhotosActivity.java:271)
        at com.huantansheng.easyphotos.ui.EasyPhotosActivity.launchCamera(EasyPhotosActivity.java:255)
        at com.huantansheng.easyphotos.ui.EasyPhotosActivity.onClick(EasyPhotosActivity.java:593)
        at android.view.View.performClick(View.java:6291)
        at android.view.View$PerformClick.run(View.java:24931)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
