### ISSUE TITLE
相册(支持video和gif)，点击相机拍照返回崩溃

### ISSUE THREAD

**Issue by SMask** [HuanTanSheng/EasyPhotos#51]
相册(支持video和gif)，点击相机拍照，完成后崩溃
```
2019-03-25 10:32:37.318 17615-17615/com.huantansheng.easyphotos.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.huantansheng.easyphotos.demo, PID: 17615
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=11, result=-1, data=null} to activity {com.huantansheng.easyphotos.demo/com.huantansheng.easyphotos.ui.EasyPhotosActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.huantansheng.easyphotos.models.album.entity.AlbumItem.addImageItem(int, com.huantansheng.easyphotos.models.album.entity.Photo)' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4222)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4265)
        at android.app.ActivityThread.-wrap20(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1614)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6388)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:930)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:820)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.huantansheng.easyphotos.models.album.entity.AlbumItem.addImageItem(int, com.huantansheng.easyphotos.models.album.entity.Photo)' on a null object reference
        at com.huantansheng.easyphotos.ui.EasyPhotosActivity.addNewPhoto(EasyPhotosActivity.java:388)
        at com.huantansheng.easyphotos.ui.EasyPhotosActivity.onCameraResult(EasyPhotosActivity.java:462)
        at com.huantansheng.easyphotos.ui.EasyPhotosActivity.onActivityResult(EasyPhotosActivity.java:336)
        at android.app.Activity.dispatchActivityResult(Activity.java:7118)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4218)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4265) 
        at android.app.ActivityThread.-wrap20(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1614) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:163) 
        at android.app.ActivityThread.main(ActivityThread.java:6388) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:930) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:820) 

```

**Comment by joker-fu** [comment]
@SMask 我的锅 已提PR
