### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by songsongtao** [HuanTanSheng/EasyPhotos#70]
`java.lang.ArrayIndexOutOfBoundsException: length=10; index=10
	at java.util.ArrayList.add(ArrayList.java:468)
	at com.huantansheng.easyphotos.models.album.entity.AlbumItem.addImageItem(AlbumItem.java:24)
	at com.huantansheng.easyphotos.models.album.AlbumModel.initAlbum(AlbumModel.java:164)
	at com.huantansheng.easyphotos.models.album.AlbumModel.access$000(AlbumModel.java:31)
	at com.huantansheng.easyphotos.models.album.AlbumModel$1.run(AlbumModel.java:62)
	at java.lang.Thread.run(Thread.java:780)`

设备是DRA-AL00 | 8.1.0

**Comment by songsongtao** [comment]
另外一个问题

**Comment by songsongtao** [comment]
`java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=11, result=-1, data=null} to activity {com.zwang.yaobeibei/com.huantansheng.easyphotos.ui.EasyPhotosActivity}: java.lang.RuntimeException: EasyPhotos拍照保存的图片不存在
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4326)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4369)
	at android.app.ActivityThread.-wrap20(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1694)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6381)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:829)
Caused by: java.lang.RuntimeException: EasyPhotos拍照保存的图片不存在
	at com.huantansheng.easyphotos.ui.EasyPhotosActivity.onActivityResult(EasyPhotosActivity.java:334)
	at android.app.Activity.dispatchActivityResult(Activity.java:7023)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4322)
	... 9 more`

**Comment by songsongtao** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.huantansheng.easyphotos.models.album.entity.AlbumItem.addImageItem(com.huantansheng.easyphotos.models.album.entity.Photo)' on a null object reference
	at com.huantansheng.easyphotos.models.album.AlbumModel.initAlbum(AlbumModel.java:190)
	at com.huantansheng.easyphotos.models.album.AlbumModel.access$000(AlbumModel.java:32)
	at com.huantansheng.easyphotos.models.album.AlbumModel$1.run(AlbumModel.java:63)
	at java.lang.Thread.run(Thread.java:764)

**Comment by joker-fu** [comment]
你这是哪个版本？

**Comment by HuanTanSheng** [comment]
@songsongtao 如果方便，麻烦加一下qq群288600953一起交流讨论，以便我们更快地解决这个问题，可以么？

**Comment by HuanTanSheng** [comment]
@songsongtao 测了一天，并没有复现，如果方便，麻烦加一下qq群288600953一起交流讨论，以便我们更快地解决这个问题，可以么？

**Comment by lingyunzhu** [comment]
@songsongtao 这个ArrayIndexOutOfBoundsException问题目测是ArrayList多线程读写造成的，可以考虑使用CopyOnWriteArrayList代替ArrayList
