### ISSUE TITLE
在选择图片的时候点击所有图片收回的时候崩溃了

### ISSUE THREAD

**Issue by SmallStoneDD** [HuanTanSheng/EasyPhotos#71]
java.lang.ClassCastException: com.huantansheng.easyphotos.ui.EasyPhotosActivity$5 cannot be cast to android.animation.Animator$AnimatorListener
        at android.animation.AnimatorSet.start(AnimatorSet.java:737)
        at android.animation.AnimatorSet.start(AnimatorSet.java:684)
        at com.huantansheng.easyphotos.ui.EasyPhotosActivity.showAlbumItems(EasyPhotosActivity.java:664)
        at com.huantansheng.easyphotos.ui.EasyPhotosActivity.onAlbumItemClick(EasyPhotosActivity.java:704)
        at com.huantansheng.easyphotos.ui.adapter.AlbumItemsAdapter$1.onClick(AlbumItemsAdapter.java:94)
        at android.view.View.performClick(View.java:6329)
        at android.view.View$PerformClick.run(View.java:25002)
        at android.os.Handler.handleCallback(Handler.java:809)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7555)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)

**Comment by HuanTanSheng** [comment]
抱歉，无法复现，希望可以到交流群进一步交流解决，Q群号：288600953
