### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by Hasiy** [HuanTanSheng/EasyPhotos#84]
荣耀 V9 小米 Max 2 畅享 Max 出现这样的问题：

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.huantansheng.easyphotos.models.album.entity.AlbumItem.addImageItem(com.huantansheng.easyphotos.models.album.entity.Photo)' on a null object reference
    at com.huantansheng.easyphotos.models.album.AlbumModel.initAlbum(AlbumModel.java:199)
    at com.huantansheng.easyphotos.models.album.AlbumModel.access$000(AlbumModel.java:30)
    at com.huantansheng.easyphotos.models.album.AlbumModel$1.run(AlbumModel.java:61)
    at java.lang.Thread.run(Thread.java:784)

**Comment by HuanTanSheng** [comment]
@Hasiy 你好，我做了一些处理，但因为没有测试机，所以需要麻烦Hasiy下载一下最新代码或apk进行测试，然后反馈一下，谢谢

**Comment by Hasiy** [comment]
好的，我去更新测试下。

**Comment by CheersJun** [comment]
反馈一个问题，这问题现实出现的概率比较小，发现清空测试机相册图库的所有图片，这时进入相册图库页面会直接crash：
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.PackageItemInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:605)
	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:417)
	at com.huantansheng.easyphotos.ui.EasyPhotosActivity.toAndroidCamera(EasyPhotosActivity.java:275)
	at com.huantansheng.easyphotos.ui.EasyPhotosActivity.launchCamera(EasyPhotosActivity.java:259)
	at com.huantansheng.easyphotos.ui.EasyPhotosActivity.initView(EasyPhotosActivity.java:483)
	at com.huantansheng.easyphotos.ui.EasyPhotosActivity.onAlbumWorkedDo(EasyPhotosActivity.java:476)
	at com.huantansheng.easyphotos.ui.EasyPhotosActivity.access$000(EasyPhotosActivity.java:70)
	at com.huantansheng.easyphotos.ui.EasyPhotosActivity$1$1.run(EasyPhotosActivity.java:169)

**Comment by HuanTanSheng** [comment]
已修复，请用2.5.0版本
